### ISSUE TITLE
no linux/serial.h

### ISSUE THREAD

**Issue by Philippe59710fr** [alerighi/modbus-sniffer#8]
unavail in std libs, unable to compile.

**Comment by alerighi** [comment]
Hi! 

On which Linux distribution are you trying to compile the program?

**Comment by Philippe59710fr** [comment]
Hi Alerighi, 
It's in a Alpine container ( HomeAssistant OS )

**Comment by alerighi** [comment]
Alpine Linux doesn't use Glibc but rather uses muslibc. I think that is the issue, since that particular headers are only available on Glibc. I should probably adjust the `#ifdef` condition to be more specific. 

Meanwhile you can just edit the source code and remove the code between the `#ifdef __linux__`. That particolar system call is not necessary for the software to work.

**Comment by alerighi** [comment]
I've added a check that ensures that include file is not present. Since this is associated with an optional feature we can just ignore it if not present.
